# -*- coding: utf-8 -*-
"""
Build self-hosted, subsetted icon fonts.

Font Awesome ships ~255 KB of webfonts and Bootstrap Icons ~90 KB, but this
site uses only a fraction of the glyphs. This script cuts each font down to
exactly the glyphs referenced in the source, writes them to
public/assets/fonts/, and emits CSS identical to the upstream file except that
the @font-face src points at the local subset.

The CSS keeps every upstream rule (utilities, sizing, animations and all icon
content rules), so nothing about how icons look or behave changes - only the
font payload shrinks.

Run from the repo root:
    python scripts/iconsubset/collect.py
    python scripts/iconsubset/build.py
"""
import io
import os
import json
import re
import shutil

from fontTools import subset

ROOT = "."
OUT_FONT_DIR = os.path.join(ROOT, "public", "assets", "fonts", "icons")
OUT_CSS_DIR = os.path.join(ROOT, "public", "assets", "fonts")

FA_DIR = os.path.join(ROOT, "node_modules", "@fortawesome", "fontawesome-free")
BI_DIR = os.path.join(ROOT, "node_modules", "bootstrap-icons", "font")

GLYPHS = json.load(io.open(os.path.join(ROOT, "scripts", "iconsubset", "glyphs.json"), encoding="utf-8"))


def subset_font(src, dst, codepoints):
    """Cut `src` down to `codepoints` and write a woff2 to `dst`."""
    unicodes = [int(c, 16) for c in codepoints]
    args = [
        src,
        "--unicodes=" + ",".join("U+%04X" % u for u in unicodes),
        "--flavor=woff2",
        "--output-file=" + dst,
        "--layout-features=",
        "--no-hinting",
        "--desubroutinize",
        "--drop-tables+=DSIG",
        "--name-IDs=",
        "--notdef-outline",
    ]
    subset.main(args)
    return os.path.getsize(src), os.path.getsize(dst)


def rewrite_css(src_css, replacements, out_path, header):
    """Copy upstream CSS, repointing @font-face src at the local subsets."""
    css = io.open(src_css, encoding="utf-8").read()

    def make_src(local_file):
        return 'src:url(/assets/fonts/icons/%s?v=2) format("woff2")' % local_file

    # "Font Awesome 6 Free" has TWO faces - weight 400 (regular) and weight 900
    # (solid) - so the family name alone is not enough to tell them apart.
    # Matching on weight as well keeps `far` icons rendering as regular instead
    # of silently falling back to their solid twins.
    def rewrite_one(family_marker, weight, local_file):
        weight_clause = r"[^}]*?font-weight:\s*%s\b" % weight if weight else ""
        pattern = re.compile(
            r"(@font-face\s*\{[^}]*?font-family:\s*[\"']?%s[\"']?%s[^}]*?)src:[^;}]+"
            % (re.escape(family_marker), weight_clause),
            re.I | re.S,
        )
        return pattern.subn(lambda m: m.group(1) + make_src(local_file), css)

    for (family_marker, weight), local_file in replacements.items():
        css, n = rewrite_one(family_marker, weight, local_file)
        label = "%s%s" % (family_marker, (" %s" % weight) if weight else "")
        if n == 0:
            print("   WARNING: no @font-face matched for %s" % label)
        else:
            print("   repointed %d @font-face rule(s) for %-28s -> %s" % (n, label, local_file))

    io.open(out_path, "w", encoding="utf-8").write(header + css)


def main():
    os.makedirs(OUT_FONT_DIR, exist_ok=True)
    os.makedirs(OUT_CSS_DIR, exist_ok=True)

    total_before = 0
    total_after = 0

    print("Font Awesome:")
    jobs = [
        (os.path.join(FA_DIR, "webfonts", "fa-solid-900.ttf"),
         os.path.join(OUT_FONT_DIR, "fa-solid-900.subset.woff2"), GLYPHS["solid"]),
        (os.path.join(FA_DIR, "webfonts", "fa-brands-400.ttf"),
         os.path.join(OUT_FONT_DIR, "fa-brands-400.subset.woff2"), GLYPHS["brands"]),
        # `far` / `fa-regular` is used across the site. The regular face shares
        # codepoints with solid, so feed it the same set - fontTools keeps only
        # the glyphs this font actually contains.
        (os.path.join(FA_DIR, "webfonts", "fa-regular-400.ttf"),
         os.path.join(OUT_FONT_DIR, "fa-regular-400.subset.woff2"), GLYPHS["solid"]),
    ]
    for src, dst, cps in jobs:
        if not cps:
            continue
        b, a = subset_font(src, dst, cps)
        total_before += b
        total_after += a
        print("   %-24s %7.1f KB -> %6.1f KB  (%d glyphs)"
              % (os.path.basename(src), b / 1024, a / 1024, len(cps)))

    rewrite_css(
        os.path.join(FA_DIR, "css", "all.min.css"),
        {("Font Awesome 6 Free", "900"): "fa-solid-900.subset.woff2",
         ("Font Awesome 6 Free", "400"): "fa-regular-400.subset.woff2",
         ("Font Awesome 6 Brands", None): "fa-brands-400.subset.woff2"},
        os.path.join(OUT_CSS_DIR, "fontawesome.subset.css"),
        "/* Font Awesome Free 6.1.1 - self-hosted subset. Generated by scripts/iconsubset/build.py. Do not edit by hand. */\n",
    )

    print("Bootstrap Icons:")
    if GLYPHS["bi"]:
        b, a = subset_font(
            os.path.join(BI_DIR, "fonts", "bootstrap-icons.woff"),
            os.path.join(OUT_FONT_DIR, "bootstrap-icons.subset.woff2"),
            GLYPHS["bi"],
        )
        total_before += b
        total_after += a
        print("   %-24s %7.1f KB -> %6.1f KB  (%d glyphs)"
              % ("bootstrap-icons.woff2", b / 1024, a / 1024, len(GLYPHS["bi"])))

    rewrite_css(
        os.path.join(BI_DIR, "bootstrap-icons.css"),
        {("bootstrap-icons", None): "bootstrap-icons.subset.woff2"},
        os.path.join(OUT_CSS_DIR, "bootstrap-icons.subset.css"),
        "/* Bootstrap Icons 1.13.1 - self-hosted subset. Generated by scripts/iconsubset/build.py. Do not edit by hand. */\n",
    )

    print("\nTOTAL font payload: %.1f KB -> %.1f KB  (saved %.1f KB)"
          % (total_before / 1024, total_after / 1024, (total_before - total_after) / 1024))


if __name__ == "__main__":
    main()
