import React from "react";
import Link from "next/link";
import BannerForm from "@/comps/BannerForm";
import Breadcrumb from "@/comps/BreadCrumb";
import Solution from "@/comps/WhiteLabel/Solution";
import WhySIB from "@/comps/Home/WhySIB";
import SIBPower from "@/comps/Home/SIBPower";
import Partnership from "@/comps/WhiteLabel/Partnership";
import PartnerBadges from "@/comps/Home/PartnerBadges2";
import OurClients from "@/comps/Home/OurClients";
import Testimonials from "@/comps/Home/Testimonials";
import Faq from "@/comps/Home/Faq";
import RelatedServices from "@/comps/RelatedServices";

const GooglePenaltyRecoveryMgt = () => {
  const penaltyServices = [
    {
      title: `Free Penalty <br class="d-none d-md-lg "/> Diagnosis`,
      description:
        "We review your Google Search Console data, traffic trends, and known algorithm update dates to determine whether you have a manual action or an algorithmic impact, and identify the probable cause.",
      img: "/assets/images/seo/technical-seo-idea-2-FINAL 1.webp",
    },
    {
      title: `Backlink Audit <br class="d-none d-md-lg "/> (Link-Related)`,
      description:
        "Full backlink profile analysis using Semrush and Ahrefs to identify toxic, unnatural, or spammy links that may be triggering or contributing to a penalty.",
      img: "/assets/images/seo/White-Label-Off-Page-SEO-&-Link-Building 1.webp",
    },
    {
      title: `Content Audit <br class="d-none d-md-lg "/> (Content-Related)`,
      description:
        "Page-by-page content quality assessment to identify thin content, auto-generated pages, AI-generated low-quality content, or doorway pages.",
      img: "/assets/images/seo/White-Label-SEO-Content-Writing-Services 1.webp",
    },
    {
      title: `Technical Audit <br class="d-none d-md-lg "/> (Hacked or Spam)`,
      description:
        "Full technical review to identify and remove any malicious content, injected links, or spam generated by third-party attacks.",
      img: "/assets/images/seo/White-Label-On-Page-SEO-Optimization 1.webp",
    },
    {
      title: `Link Removal <br class="d-none d-md-lg "/> Campaign`,
      description:
        "Outreach to webmasters of toxic linking domains requesting link removal, followed by a precise disavow file for links that cannot be removed. We disavow only confirmed toxic links — over-disavowing can damage your link profile further.",
      img: "/assets/images/seo/White-Label-Local-SEO-Services 1.webp",
    },
    {
      title: `Content <br class="d-none d-md-lg "/> Remediation`,
      description:
        "For Helpful Content or thin content issues, we build a content quality improvement plan covering rewrites, consolidations, and removal of low-quality pages.",
      img: "/assets/images/seo/White-Label-E-Commerce-SEO-Services 1.webp",
    },
    {
      title: `Reconsideration <br class="d-none d-md-lg "/> Request`,
      description:
        "For manual actions, we write a detailed, evidence-backed reconsideration request to Google's spam team documenting all actions taken to address the policy violation.",
      img: "/assets/images/seo/White-Label-Mobile-SEO 1.webp",
    },
    {
      title: `Post-Recovery <br class="d-none d-md-lg "/> Monitoring`,
      description:
        "Following penalty removal, we monitor rankings and traffic weekly and provide a clean bill of health report once organic performance has stabilised at pre-penalty or improved levels.",
      img: "/assets/images/seo/White-Label-SEO-Content-Writing-Services 1.webp",
    },
  ];

  const warningSigns = [
    "Your organic traffic dropped sharply and suddenly (50% or more) without any changes on your end.",
    "You received a notification in Google Search Console under Security & Manual Actions.",
    "You launched a new website and notice it has no organic visibility at all.",
    "Your rankings disappeared entirely for queries where you previously ranked well.",
    "Your website was hit around the time of a known Google algorithm update.",
  ];

  const manualActionTypes = [
    "Unnatural links to your site: Artificial, purchased, or manipulative backlinks pointing to your site.",
    "Unnatural links from your site: Outbound links that violate Google's link spam policies.",
    "Thin content with little or no added value: Pages that provide minimal value to users.",
    "Hacked site: Malicious content injected into your site by third parties.",
    "User-generated spam: Spam in comments, forums, or profile pages on your website.",
    "Pure spam: A site entirely dedicated to manipulative tactics.",
  ];

  const algorithmicTypes = [
    {
      title: "Google Core Updates",
      description:
        "Broad quality reassessments that can reward or suppress sites based on overall content quality, EEAT, and user experience signals.",
    },
    {
      title: "Helpful Content System",
      description:
        "A site-wide signal that rewards original, expert-created content and suppresses low-quality, auto-generated, or formulaic content.",
    },
    {
      title: "Google Spam Update",
      description:
        "Targets manipulative link schemes, scaled content abuse, and site reputation abuse.",
    },
    {
      title: "Penguin",
      description:
        "Part of the core algorithm that devalues manipulative link profiles. Now runs in real time.",
    },
  ];

  const recoverySteps = [
    {
      title: "Free Penalty Diagnosis",
      description:
        "We review your Google Search Console data, traffic trends, and known algorithm update dates to determine whether you have a manual action or an algorithmic impact, and identify the probable cause.",
    },
    {
      title: "Backlink Audit (Link-Related)",
      description:
        "Full backlink profile analysis using Semrush and Ahrefs to identify toxic, unnatural, or spammy links that may be triggering or contributing to a penalty.",
    },
    {
      title: "Content Audit (Content-Related)",
      description:
        "Page-by-page content quality assessment to identify thin content, auto-generated pages, AI-generated low-quality content, or doorway pages.",
    },
    {
      title: "Technical Audit (Hacked or Spam)",
      description:
        "Full technical review to identify and remove any malicious content, injected links, or spam generated by third-party attacks.",
    },
    {
      title: "Link Removal Campaign",
      description:
        "Outreach to webmasters of toxic linking domains requesting link removal.",
    },
    {
      title: "Disavow File Submission",
      description:
        "For links that cannot be removed, we build a precise disavow file for submission through Google Search Console. We disavow only confirmed toxic links — over-disavowing can damage your link profile further.",
    },
    {
      title: "Content Remediation",
      description:
        "For Helpful Content or thin content issues, we build a content quality improvement plan covering rewrites, consolidations, and removal of low-quality pages.",
    },
    {
      title: "Reconsideration Request (Manual Actions)",
      description:
        "We write a detailed, evidence-backed reconsideration request to Google's spam team documenting all actions taken to address the policy violation.",
    },
    {
      title: "Post-Recovery Monitoring",
      description:
        "Following penalty removal, we monitor rankings and traffic weekly and provide a clean bill of health report once organic performance has stabilised at pre-penalty or improved levels.",
    },
  ];

  const timelineTable = [
    {
      type: "Manual action (link-related)",
      timeline: "2-4 months",
      notes:
        "Dependent on link removal and reconsideration request review time",
    },
    {
      type: "Manual action (content-related)",
      timeline: "1-3 months",
      notes: "Faster if content issues are resolved quickly",
    },
    {
      type: "Core Update algorithmic impact",
      timeline: "2-6 months",
      notes: "Recovery aligns with the next relevant core update release",
    },
    {
      type: "Helpful Content System",
      timeline: "2-4 months",
      notes: "Site-wide signal: improving overall content quality required",
    },
    {
      type: "Hacked site",
      timeline: "1-2 months",
      notes:
        "Faster once malicious content is fully removed and reported to Google",
    },
  ];

  const keyAdvantages = [
    {
      title: "Google Premier Partner Since 2005",
      description:
        "Among the top 3% of Google Partners in India, with direct access to Google insights and beta features.",
    },
    {
      title: "18+ Years of Expertise",
      description:
        "Proven performance across every major algorithm era, from Panda and Penguin through AI Overviews and generative search.",
    },
    {
      title: "850+ Active Clients Across 40+ Countries",
      description:
        "Our strategies are stress-tested across industries and markets worldwide.",
    },
    {
      title: "Named Enterprise Clients",
      description:
        "Trusted by Airtel, Finolex, Jindal Steel, and BPCL for their digital growth.",
    },
    {
      title: "Full-Service Team",
      description:
        "Technical SEOs, content specialists, link builders, and strategists working as one integrated unit.",
    },
    {
      title: "Transparent Monthly Reporting",
      description:
        "Keyword rankings, traffic trends, and ROI analysis delivered every month.",
    },
  ];

  const leftBoxContent = {
    headingStart: "Why Businesses Choose ",
    headingHighlight: "SIB Infotech",
    subHeading: "Precise Diagnosis. Methodical Recovery. Proven Track Record.",
    cardTitle: "Recover Rankings With a Documented Methodology",
    cardDescription:
      "A Google penalty can drop your organic traffic by 50% to 100% overnight. Every day without a fix is revenue lost permanently. SIB Infotech has recovered rankings for businesses across India following both manual penalties and algorithmic updates — with a documented methodology and an 18-year track record.",
    buttonText: "Get Your Free Penalty Diagnosis",
  };

  const rightBoxContent = {
    heading: "The Penalty Recovery Team That Diagnoses Before It Acts",
    description:
      "Google penalty recovery requires careful diagnosis before any action. Different penalty types require different treatments. SIB Infotech has 18+ years of Google algorithm experience — we diagnose precisely before we act, and we have recovered rankings for businesses across India following both manual penalties and algorithmic updates.",
  };

  const power_data = [
    {
      title: "Precise Diagnosis Before Any Action",
      description:
        "We determine whether you have a manual action or an algorithmic impact — and which policy or quality signal triggered it — before we touch anything.",
    },
    {
      title: "Careful Disavow Strategy",
      description:
        "We disavow only confirmed toxic links. Over-disavowing permanently removes legitimate authority you cannot recover.",
    },
    {
      title: "Google Premier Partner (Top 3% in India)",
      description:
        "Among the top 3% of Google Partners in India with direct access to Google insights, AI Overviews intelligence, and beta features.",
    },
    {
      title: "18+ Years Across Every Algorithm Era",
      description:
        "From Panda and Penguin through Helpful Content and AI Overviews, our recovery methodology has been battle-tested through every major update.",
    },
    {
      title: "Evidence-Backed Reconsideration Requests",
      description:
        "Detailed, evidence-backed reconsideration requests that document every action taken to address the policy violation.",
    },
    {
      title: "Dedicated Account Manager — Not a Support Ticket",
      description:
        "A dedicated strategist assigned to your account, reachable on call, WhatsApp, and email with deep knowledge of your recovery goals.",
    },
  ];

  const agencyWorkflow = [
    {
      title: "Free Diagnosis",
      description: `<p>Traffic analysis, GSC manual action check, and algorithm update timeline correlation.</p>`,
    },
    {
      title: "Full Audit",
      description: `<p>Backlink profile, content quality, and technical health assessment.</p>`,
    },
    {
      title: "Recovery Plan",
      description: `<p>Detailed plan covering link removal, disavow strategy, content remediation, or technical fixes depending on penalty type.</p>`,
    },
    {
      title: "Execution",
      description: `<p>Link removal outreach, disavow file preparation, content rewrites, or technical resolution.</p>`,
    },
    {
      title: "Reconsideration Request",
      description: `<p>For manual actions, drafted and submitted to Google's spam review team.</p>`,
    },
    {
      title: "Post-Recovery Monitoring",
      description: `<p>Weekly tracking of organic traffic, rankings, and GSC status for 90 days post-recovery.</p>`,
    },
  ];

  const faqsData = [
    {
      id: "faq1",
      question: "How do I know if my website has a Google penalty?",
      answer: `<p>The most reliable indicator is a notification in Google Search Console under Security & Manual Actions. For algorithmic impacts, there is no notification — you will see a sharp organic traffic drop correlated with a known Google algorithm update date. We offer a free penalty diagnosis to determine which type of issue you are dealing with.</p>`,
    },
    {
      id: "faq2",
      question: "Can a Google penalty be reversed?",
      answer: `<p>Yes. Manual actions can be reversed by fixing the policy violation and submitting a successful reconsideration request to Google. Algorithmic impacts can be recovered from by improving the quality signals that the algorithm is penalising, with recovery typically occurring at the next relevant algorithm update.</p>`,
    },
    {
      id: "faq3",
      question: "How much does Google penalty recovery cost?",
      answer: `<p>Penalty recovery is priced on a case-by-case basis depending on the type of penalty, the size of the backlink profile to audit, and the extent of content remediation required. We provide a free diagnosis and scope assessment before any cost discussion.</p>`,
    },
    {
      id: "faq4",
      question: "What if I bought backlinks and now have a link penalty?",
      answer: `<p>Paid link schemes are a common cause of Google manual actions and algorithmic suppression. The fix involves documenting and removing as many purchased links as possible and disavowing the remainder through Google Search Console. We handle both the removal outreach and the disavow file preparation.</p>`,
    },
    {
      id: "faq5",
      question: "Will my site fully recover to its pre-penalty rankings?",
      answer: `<p>Most websites recover to near pre-penalty levels following thorough remediation. However, recovery outcomes depend on the severity of the violation, how long the penalty has been in place, what competitors have done in the meantime, and the quality of the content and backlink profile after remediation.</p>`,
    },
  ];

  return (
    <div>
      {/* Hero Banner */}
      <div className="innerWebDesign whiteLable" id="contact">
        <div className="container-fluid">
          <div className="row">
            <div className="col-lg-7 ps-lg-5">
              <div className="innerBannerTitle venter">
                <h1 className="mt-3 heading fontWeight700 text-white">
                  Google Penalty Recovery: Diagnose,{" "}
                  <span className="text_red fontWeight700">
                    Fix, and Restore Your Rankings
                  </span>
                </h1>
                <p
                  className="small_heading fontWeight500 mt-2 text-white"
                  style={{ maxWidth: "85%" }}
                >
                  Google Premier Partner | 18+ Years Experience | 850+ Active
                  Clients in 40+ Countries
                </p>
                <p className="mt-2 mt-lg-3 text-white" style={{ maxWidth: "85%" }}>
                  A Google penalty can drop your organic traffic by 50% to 100%
                  overnight. Every day without a fix is revenue lost
                  permanently. SIB Infotech has recovered rankings for
                  businesses across India following both manual penalties and
                  algorithmic updates — with a documented methodology and an
                  18-year track record.
                </p>
                <p className="mt-2 mt-lg-3 text-white small fw-bold" style={{ maxWidth: "85%" }}>
                  <i className="fa-solid fa-circle-exclamation me-2"></i>
                  Google penalty recovery is time-sensitive. Every day of
                  suppressed rankings represents direct business loss.
                </p>
                <div className="mt-4">
                  <Link href="/contact-us" className="btnThemeRed me-3">
                    <i className="fa-solid fa-comment-dots me-2"></i> Get a Quote
                  </Link>
                  <Link href="/contact-us" className="btnThemewhiteBorder">
                    <i className="fa-solid fa-circle-question me-2"></i> Ask a
                    Question
                  </Link>
                </div>
              </div>
            </div>

            <div className="col-lg-5 d-none d-lg-block pe-lg-5">
              <div className="bannerForm">
                <h4 className="small_heading fontWeight700">
                  Get Your Free Penalty Diagnosis
                </h4>
                <p>
                  with{" "}
                  <strong className="fontWeight600 text_red">
                    Google Penalty Experts in India
                  </strong>
                </p>
                <BannerForm />
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="d-lg-none">
        <Breadcrumb Pagetitle={"Google Penalty Recovery"} />
      </div>
      <div className="col-lg-5 d-block d-lg-none pe-lg-5">
        <div className="bannerForm">
          <h4 className="small_heading fontWeight700">
            Get Your Free Penalty Diagnosis
          </h4>
          <p>
            with{" "}
            <strong className="fontWeight600 text_red">
              Google Penalty Experts in India
            </strong>
          </p>
          <BannerForm />
        </div>
      </div>
      <div className="d-none d-lg-block">
        <Breadcrumb Pagetitle={"Google Penalty Recovery"} />
      </div>

      {/* Has Your Website Been Hit by a Google Penalty? */}
      <section>
        <div className="containerFull">
          <div className="row align-items-center">
            <div className="col-lg-7">
              <h2 className="heading fontWeight600">
                Has Your Website Been{" "}
                <span className="text_red">Hit by a Google Penalty?</span>
              </h2>
              <p className="customText mt-3">
                You may have received a Google penalty if you are experiencing
                any of the warning signs below. Time matters — the longer a
                penalty persists unaddressed, the more secondary damage
                accumulates: backlinks pointing to penalised pages lose
                effectiveness, brand search volume declines, and competitors
                cement their positions in the rankings you used to hold. Not
                sure whether your ranking drop is penalty-related or caused by
                a technical fault? Start with a{" "}
                <Link href="/seo-audit-services" className="text_red">
                  complete SEO audit
                </Link>{" "}
                to diagnose the root cause before we build your recovery plan.
              </p>
              <ul className="list-unstyled mt-3">
                {warningSigns.map((item, index) => (
                  <li className="mb-3" key={index}>
                    <i className="fa-solid fa-circle-exclamation text_red me-2"></i>
                    {item}
                  </li>
                ))}
              </ul>
            </div>
            <div className="col-lg-5 mt-4 mt-lg-0">
              <div className="customCard bgGrey2">
                <h3 className="small_heading fontWeight600 mb-3">
                  Why Immediate Action Matters
                </h3>
                <p className="customText">
                  The longer a penalty persists unaddressed, the more secondary
                  damage accumulates:
                </p>
                <ul className="list-unstyled">
                  <li className="mb-3">
                    <strong>Backlink erosion:</strong> Links pointing to
                    penalised pages lose effectiveness.
                  </li>
                  <li className="mb-3">
                    <strong>Brand demand decline:</strong> Brand search volume
                    drops as visibility disappears.
                  </li>
                  <li className="mb-3">
                    <strong>Competitor cementing:</strong> Competitors lock in
                    the rankings you used to hold.
                  </li>
                  <li className="mb-3">
                    <strong>Compounding revenue loss:</strong> Every day of
                    suppressed rankings represents direct business loss.
                  </li>
                </ul>
                <p className="customText mb-0">
                  We identify the type of issue and outline the recovery path
                  within 24 hours of diagnosis.
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Types of Google Penalties */}
      <section className="bgGrey2">
        <div className="containerFull">
          <div className="row justify-content-center text-center mb-5">
            <div className="col-lg-9">
              <h2 className="heading fontWeight600">
                Types of{" "}
                <span className="text_red">Google Penalties</span>
              </h2>
              <p className="customText mt-3">
                Penalties fall into two categories. Correct diagnosis of the
                type is the first step to recovery:
              </p>
            </div>
          </div>

          <div className="row g-4 mt-2">
            <div className="col-lg-6">
              <div className="off-page-seo-box2 h-100">
                <h4 className="small_heading fontWeight600 mb-2">
                  Manual Actions (Manual Penalties)
                </h4>
                <p className="customText">
                  A Google manual action is applied by a human Google Search
                  Quality reviewer who has determined that your website violates
                  Google's spam policies. Manual actions are always visible in
                  Google Search Console under Security & Manual Actions.
                </p>
                <ul className="list-unstyled">
                  <li className="mb-2">
                    <i className="fa-solid fa-circle-exclamation text_red me-2"></i>
                    Unnatural links to your site
                  </li>
                  <li className="mb-2">
                    <i className="fa-solid fa-circle-exclamation text_red me-2"></i>
                    Unnatural links from your site
                  </li>
                  <li className="mb-2">
                    <i className="fa-solid fa-circle-exclamation text_red me-2"></i>
                    Thin content with little or no added value
                  </li>
                  <li className="mb-2">
                    <i className="fa-solid fa-circle-exclamation text_red me-2"></i>
                    Hacked site
                  </li>
                  <li className="mb-2">
                    <i className="fa-solid fa-circle-exclamation text_red me-2"></i>
                    User-generated spam
                  </li>
                  <li className="mb-2">
                    <i className="fa-solid fa-circle-exclamation text_red me-2"></i>
                    Pure spam
                  </li>
                </ul>
              </div>
            </div>
            <div className="col-lg-6">
              <div className="off-page-seo-box2 h-100">
                <h4 className="small_heading fontWeight600 mb-2">
                  Algorithmic Penalties (Algorithm Hits)
                </h4>
                <p className="customText">
                  Algorithmic penalties are not manually applied. Instead, your
                  site loses rankings when Google releases an algorithm update
                  that re-evaluates sites based on new criteria. Common
                  algorithm updates that cause traffic drops:
                </p>
                <ul className="list-unstyled">
                  {algorithmicTypes.map((item, index) => (
                    <li className="mb-3" key={index}>
                      <i className="fa-solid fa-circle-exclamation text_red me-2"></i>
                      <strong>{item.title}:</strong> {item.description}
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Our Google Penalty Recovery Process */}
      <section>
        <div className="containerFull">
          <div className="row justify-content-center text-center mb-5">
            <div className="col-lg-9">
              <h2 className="heading fontWeight600">
                Our Google Penalty{" "}
                <span className="text_red">Recovery Process</span>
              </h2>
              <p className="customText mt-3">
                Every recovery follows a structured, diagnosis-first methodology
                tailored to the type of penalty affecting your site:
              </p>
            </div>
          </div>

          <div className="row g-4 mt-2">
            {recoverySteps.map((item, index) => (
              <div className="col-lg-4 col-md-6" key={index}>
                <div className="customCard h-100">
                  <div className="heading fontWeight700 text_red mb-2">
                    {String(index + 1).padStart(2, "0")}
                  </div>
                  <h4 className="small_heading fontWeight600 mb-2">
                    {item.title}
                  </h4>
                  <p className="customText mb-0">{item.description}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Recovery Timeline */}
      <section className="bgGrey">
        <div className="containerFull">
          <div className="row justify-content-center text-center mb-4">
            <div className="col-lg-8">
              <h2 className="heading fontWeight600">
                How Long Does Google{" "}
                <span className="text_red">Penalty Recovery Take?</span>
              </h2>
              <p className="customText mt-3">
                Recovery timelines depend on the penalty type and the speed and
                completeness of remediation:
              </p>
            </div>
          </div>

          <div className="row justify-content-center">
            <div className="col-lg-10">
              <div className="table-responsive">
                <table className="table table-bordered align-middle mb-0 bg-white">
                  <thead>
                    <tr>
                      <th className="bgRedMenu text-white p-3">Penalty Type</th>
                      <th className="bgRedMenu text-white p-3">
                        Typical Recovery Timeline
                      </th>
                      <th className="bgRedMenu text-white p-3">Notes</th>
                    </tr>
                  </thead>
                  <tbody>
                    {timelineTable.map((item, index) => (
                      <tr key={index}>
                        <td className="p-3">
                          <strong>{item.type}</strong>
                        </td>
                        <td className="p-3">{item.timeline}</td>
                        <td className="p-3">{item.notes}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
              <p className="customText mt-3 mb-0">
                Recovery timelines assume prompt and thorough action. Partial
                fixes or incomplete link removal significantly extend recovery
                time.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Why Google Penalties Are Not a DIY Fix */}
      <section>
        <div className="containerFull">
          <div className="row justify-content-center text-center mb-5">
            <div className="col-lg-9">
              <h2 className="heading fontWeight600">
                Why Google Penalties Are{" "}
                <span className="text_red">Not a DIY Fix</span>
              </h2>
              <p className="customText mt-3">
                Google penalty recovery requires careful diagnosis before any
                action. These are the most common mistakes that extend recovery
                time:
              </p>
            </div>
          </div>

          <p className="customText mt-4 text-center">
            SIB Infotech has 18+ years of Google algorithm experience. We
            diagnose precisely before we act.
          </p>
        </div>
      </section>

      {/* Why Choose SIB Infotech */}
      <WhySIB
        keyAdvantages={keyAdvantages}
        leftBoxContent={leftBoxContent}
        rightBoxContent={rightBoxContent}
      />

      <SIBPower
        title="Why Choose SIB Infotech for Google Penalty Recovery"
        description_right="Recovering from a Google penalty is a precise, high-stakes process. Here is why 850+ businesses across 40+ countries trust SIB Infotech."
        data={power_data}
      />

      {/* Our Process */}
      <Partnership
        agencyWorkflow={agencyWorkflow}
        title={"Our Google Penalty Recovery Process"}
        rightDiscription={
          "Every engagement follows a structured, diagnosis-first methodology designed to restore rankings and organic revenue."
        }
      />

      {/* Certifications & Badges */}
      <PartnerBadges />

      {/* Final CTA */}
      <section className="bgGrey py-5">
        <div className="containerFull">
          <div className="row align-items-center">
            <div className="col-lg-7">
              <h2 className="heading fontWeight600">
                Get Your Free{" "}
                <span className="text_red">Penalty Diagnosis</span>
              </h2>
              <p className="customText mt-3">
                If your organic traffic has dropped sharply and unexpectedly, do
                not wait. Contact our team for a free penalty diagnosis — we
                will identify the type of issue and outline the recovery path
                within 24 hours.
              </p>
              <div className="mt-4">
                <Link href="/contact-us" className="btnThemeRed me-3">
                  <i className="fa-solid fa-comment-dots me-2"></i> Get My Free
                  Penalty Diagnosis Now
                </Link>
                <Link
                  href="tel:+912226057575"
                  className="btnThemewhiteBorder"
                >
                  <i className="fa-solid fa-phone me-2"></i> +91 22 2605 7575
                </Link>
              </div>
              <p className="customText mt-4 mb-0">
                Contact SIB Infotech:{" "}
                <a href="mailto:info@sibinfotech.com" className="text_red">
                  info@sibinfotech.com
                </a>
              </p>
            </div>
            <div className="col-lg-5 mt-4 mt-lg-0">
              <div className="customCard bg-white">
                <h4 className="small_heading fontWeight700 text-center mb-3">
                  Request Your Free Penalty Diagnosis
                </h4>
                <BannerForm />
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Client Logos & Testimonials */}
      <OurClients />
      <Testimonials />

      {/* FAQs */}
      <Faq
        title={"Frequently Asked Questions about Google Penalty Recovery"}
        description={
          "Everything you need to know about recovering from Google penalties."
        }
        faqsData={faqsData}
      />

      {/* Related Services */}
      <RelatedServices
        subtitle={
          "Explore more SEO services that protect and grow your rankings."
        }
        links={[
          {
            title: "SEO Company in Mumbai",
            description:
              "Our flagship SEO service. Google Premier Partner, 20+ years, ranking Mumbai businesses since 2005.",
            href: "/seo-company-mumbai",
          },
          {
            title: "SEO Audit Services",
            href: "/seo-audit-services",
            description:
              "Discover the exact issues behind your ranking loss with a complete SEO health check.",
          },
          {
            title: "Technical SEO Services",
            href: "/technical-seo-services",
            description:
              "Fix crawlability, indexation, and site architecture issues that trigger algorithm penalties.",
          },
          {
            title: "LLM SEO Services",
            href: "/llm-seo-services",
            description:
              "Rebuild visibility across AI Overviews, ChatGPT, Gemini, and Perplexity after recovery.",
          },
          {
            title: "Enterprise SEO Services",
            href: "/enterprise-seo-services",
            description:
              "Scalable SEO programmes for large websites and multi-location brands.",
          },
          {
            title: "SEO Packages and Pricing",
            href: "/seo-packages",
            description:
              "Transparent monthly SEO plans starting at Rs. 25,000 per month for businesses of every size.",
          },
          {
            title: "White Label SEO Services",
            href: "/white-label-seo-services",
            description:
              "White label penalty recovery and SEO delivery for agencies under your own brand.",
          },
        ]}
      />
    </div>
  );
};

export default GooglePenaltyRecoveryMgt;
